const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const bootstrap = require('../orch-bootstrap');

function freshClaudeDir() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sb-boot-'));
  bootstrap.setClaudeDirForTesting(dir);
  return dir;
}

const noopLog = { info: () => {}, warn: () => {}, error: () => {} };

test('first run installs the full agent pack with stamp', () => {
  const dir = freshClaudeDir();
  const res = bootstrap.ensureClaudeAssets({ log: noopLog });
  assert.equal(res.ok, true);
  assert.equal(res.updated, true);
  for (const name of ['sb-plan.md', 'sb-decompose.md', 'sb-orchestrate.md', 'sb-work.md', 'sb-review.md', 'sb-merge.md']) {
    const file = path.join(dir, 'commands', name);
    assert.ok(fs.existsSync(file), name + ' missing');
    const content = fs.readFileSync(file, 'utf8');
    assert.ok(content.startsWith('---\n'), 'frontmatter must stay at byte 0');
    assert.match(content, /Generated by Switchboard/);
  }
  const stamp = JSON.parse(fs.readFileSync(path.join(dir, bootstrap.STAMP_RELPATH), 'utf8'));
  assert.equal(stamp.hash, bootstrap.packHash(bootstrap.assetManifest()));
  assert.equal(stamp.files.length, 6);
});

test('second run is a no-op (files untouched)', () => {
  const dir = freshClaudeDir();
  bootstrap.ensureClaudeAssets({ log: noopLog });
  const file = path.join(dir, 'commands', 'sb-work.md');
  const before = fs.statSync(file).mtimeMs;
  const res = bootstrap.ensureClaudeAssets({ log: noopLog });
  assert.equal(res.updated, false);
  assert.equal(fs.statSync(file).mtimeMs, before, 'unchanged pack must not rewrite files');
});

test('deleted command is reinstalled even when the hash still matches', () => {
  const dir = freshClaudeDir();
  bootstrap.ensureClaudeAssets({ log: noopLog });
  fs.unlinkSync(path.join(dir, 'commands', 'sb-review.md'));
  const res = bootstrap.ensureClaudeAssets({ log: noopLog });
  assert.equal(res.updated, true);
  assert.ok(fs.existsSync(path.join(dir, 'commands', 'sb-review.md')));
});

test('stale or corrupt stamp triggers a refresh that overwrites local edits', () => {
  const dir = freshClaudeDir();
  bootstrap.ensureClaudeAssets({ log: noopLog });
  const file = path.join(dir, 'commands', 'sb-work.md');
  fs.writeFileSync(file, '# user broke this\n');
  fs.writeFileSync(path.join(dir, bootstrap.STAMP_RELPATH), '{"hash":"stale"}');
  const res = bootstrap.ensureClaudeAssets({ log: noopLog });
  assert.equal(res.updated, true);
  assert.match(fs.readFileSync(file, 'utf8'), /WORKER agent/);
});

test('works when ~/.claude does not exist at all (fresh machine)', () => {
  const dir = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'sb-boot-')), 'nested', '.claude');
  bootstrap.setClaudeDirForTesting(dir);
  const res = bootstrap.ensureClaudeAssets({ log: noopLog });
  assert.equal(res.ok, true);
  assert.ok(fs.existsSync(path.join(dir, 'commands', 'sb-plan.md')));
});
