const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const tpl = require('../orch-templates');

function tmpProject() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'sb-tpl-'));
}

const RUN = {
  id: '2026-06-10-demo-abcd', title: 'Demo', goal: 'build the thing',
  integrationBranch: 'teams/demo',
  roles: { master: {}, worker: {}, reviewer: {} },
};

test('installCommands writes all sb-* commands with frontmatter intact', () => {
  const project = tmpProject();
  const written = tpl.installCommands(project);
  assert.equal(written.length, 6);
  for (const name of ['sb-plan', 'sb-decompose', 'sb-orchestrate', 'sb-work', 'sb-review', 'sb-merge']) {
    const file = path.join(project, '.claude', 'commands', name + '.md');
    assert.ok(fs.existsSync(file), name + ' missing');
    const content = fs.readFileSync(file, 'utf8');
    assert.ok(content.startsWith('---\n'), name + ' frontmatter must be at byte 0');
    assert.match(content, /Generated by Switchboard Agent Teams/);
    assert.match(content, /\.switchboard\/runs/, name + ' must explain the protocol');
  }
  // idempotent overwrite
  const again = tpl.installCommands(project);
  assert.equal(again.length, 6);
});

test('ensureGuidelines creates the template once, never clobbers edits', () => {
  const project = tmpProject();
  const target = tpl.ensureGuidelines(project);
  assert.match(fs.readFileSync(target, 'utf8'), /blocker/);
  fs.writeFileSync(target, '# my rules\n');
  tpl.ensureGuidelines(project);
  assert.equal(fs.readFileSync(target, 'utf8'), '# my rules\n');
});

test('ensureOrchGitignore ignores worktrees', () => {
  const project = tmpProject();
  const target = tpl.ensureOrchGitignore(project);
  assert.match(fs.readFileSync(target, 'utf8'), /worktrees\//);
});

test('rolePrompt constrains each role', () => {
  const project = tmpProject();
  const worker = tpl.rolePrompt('worker', RUN, project, { id: 'T-1' });
  assert.match(worker, /WORKER/);
  assert.match(worker, /T-1/);
  assert.match(worker, /worktree/);
  const reviewer = tpl.rolePrompt('reviewer', RUN, project, { id: 'T-1' });
  assert.match(reviewer, /must not modify source code/);
  const master = tpl.rolePrompt('master', RUN, project, null);
  assert.match(master, /integration worktree/);
  assert.match(master, /\[switchboard\]/);
});

test('masterBootPrompt embeds run id and goal', () => {
  assert.equal(tpl.masterBootPrompt(RUN), `/sb-plan ${RUN.id} build the thing`);
});
